// Turning a Postgres or Redshift table into one a local Postgres will
// create: the column types and defaults of a copy. Pure, so it is tested
// on its own; the builder (src/builder/pg.ts) carries it out.
//
// Redshift is Postgres 8 underneath with its own storage on top. Its
// distribution and sort keys, compression encodings and IDENTITY belong to
// the cluster, not to the data, and are left behind; its types map to the
// nearest Postgres one. A Postgres source keeps its types as they are.

import type { ColumnInfo } from './types';

const BUILTIN = /^(smallint|integer|int|int2|int4|int8|bigint|real|float4|float8|double precision|numeric|decimal|boolean|bool|text|bytea|date|uuid|json|jsonb|inet|cidr|macaddr|money|interval|xml|tsvector|tsquery|oid|name|"char"|char|character|varchar|character varying|bpchar|bit|bit varying|varbit|timestamp|timestamptz|time|timetz|point|line|lseg|box|path|polygon|circle)\b/i;

/// The type a column gets in the copy.
export function pgType(typeName: string, redshift: boolean): string {
  const t = typeName.trim();
  // A type name goes into CREATE TABLE as written, so only the shape a
  // type name has — words, a size, array brackets — ever does. Anything
  // else, which no real catalog prints, is kept as text.
  if (!/^[A-Za-z_"][\w" ]*(\(\s*(\d+|max)(\s*,\s*\d+)?\s*\))?(\s+with(out)?\s+time\s+zone)?(\[\])*$/i.test(t)) return 'text';
  const lower = t.toLowerCase();
  if (redshift) {
    if (lower === 'super') return 'jsonb';
    if (/^(geometry|geography|hllsketch)/.test(lower)) return 'text';
    if (/^(varbyte|varbinary|binary varying)/.test(lower)) return 'bytea';
    // Redshift spells "no limit" as 65535; Postgres takes it as written.
    return t.replace(/\bmax\b/i, '65535');
  }
  // Arrays of a known type keep their brackets.
  if (BUILTIN.test(lower.replace(/\[\]$/, ''))) return t;
  // A user-defined type (an enum, a domain) is not created in the copy: its
  // values are kept as text, which every such type reads and writes.
  return 'text';
}

/// The column's definition after its name: type, identity, default, NOT NULL.
export function pgColumn(c: ColumnInfo, redshift: boolean): string {
  const type = pgType(c.typeName, redshift);
  const def = (c.defaultExpr ?? '').trim();
  // A sequence or Redshift IDENTITY becomes Postgres's own identity, BY
  // DEFAULT so the copied ids are kept as they are.
  const counts = /^(smallint|integer|int|int2|int4|int8|bigint)\b/i.test(type);
  if (counts && (/^nextval\(/i.test(def) || /"?identity"?\s*\(/i.test(def))) {
    return `${type} GENERATED BY DEFAULT AS IDENTITY${c.nullable ? '' : ' NOT NULL'}`;
  }
  const d = pgDefault(def, redshift);
  return `${type}${d ? ` DEFAULT ${d}` : ''}${c.nullable ? '' : ' NOT NULL'}`;
}

/// A default the copy can keep: literals, casts of literals, and the clock.
/// Anything else — a function only the source has, a sequence that is not
/// created — is left off; the rows arrive with their values anyway.
export function pgDefault(expr: string, redshift: boolean): string | null {
  const e = expr.trim();
  if (!e) return null;
  if (/^(getdate|sysdate)\s*(\(\s*\))?$/i.test(e) || /^now\(\)$/i.test(e) || /^current_(timestamp|date|time)(\(\d\))?$/i.test(e)) {
    return /^current_date/i.test(e) ? 'CURRENT_DATE' : 'now()';
  }
  if (/^\(?\s*-?\d+(\.\d+)?\s*\)?(::[\w\s"]+)?$/.test(e)) return e;
  if (/^'(?:[^']|'')*'(::[\w\s"()[\],]+)?$/.test(e)) return redshift ? e.replace(/::character varying\b/i, '::varchar') : e;
  if (/^(true|false|null)$/i.test(e)) return e;
  return null;
}

/// Quoting for an identifier, as Postgres reads it.
export function pgIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}
