import { describe, expect, it } from 'vitest';
import { pgColumn, pgDefault, pgType } from './pgCopy';

const col = (typeName: string, defaultExpr: string | null = null, nullable = true) => ({ name: 'c', ordinal: 1, typeName, nullable, defaultExpr });

describe('a Redshift column in a local Postgres', () => {
  it('maps the types Postgres does not have', () => {
    expect(pgType('super', true)).toBe('jsonb');
    expect(pgType('geometry', true)).toBe('text');
    expect(pgType('varbyte(64)', true)).toBe('bytea');
    expect(pgType('character varying(256)', true)).toBe('character varying(256)');
    expect(pgType('numeric(18,2)', true)).toBe('numeric(18,2)');
    expect(pgType('timestamp without time zone', true)).toBe('timestamp without time zone');
  });

  it('turns IDENTITY into an identity column that keeps the copied ids', () => {
    expect(pgColumn(col('bigint', '"identity"(123456, 0, \'1,1\'::text)', false), true)).toBe('bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL');
  });

  it('keeps the clock and literals, and drops what only the source has', () => {
    expect(pgDefault('getdate()', true)).toBe('now()');
    expect(pgDefault('sysdate', true)).toBe('now()');
    expect(pgDefault("'active'::character varying", true)).toBe("'active'::varchar");
    expect(pgDefault('0', true)).toBe('0');
    expect(pgDefault('f_my_udf(1)', true)).toBeNull();
    expect(pgColumn(col('integer', 'f_my_udf(1)', false), true)).toBe('integer NOT NULL');
  });
});

describe('a Postgres column in a local Postgres', () => {
  it('keeps its type, and a sequence becomes identity', () => {
    expect(pgType('uuid', false)).toBe('uuid');
    expect(pgType('text[]', false)).toBe('text[]');
    expect(pgType('timestamp with time zone', false)).toBe('timestamp with time zone');
    expect(pgColumn(col('integer', "nextval('users_id_seq'::regclass)", false), false)).toBe('integer GENERATED BY DEFAULT AS IDENTITY NOT NULL');
  });

  it('keeps a user-defined type as text', () => {
    expect(pgType('order_status', false)).toBe('text');
  });
});
